### ISSUE TITLE
Error: Mismatch between content when adding a new attribute with frontend: true

### ISSUE THREAD

**Issue by c4rl0sbr4v0** [WordPress/block-hydration-experiments#21]
## Issue found

If we add a new attribute to the block, everything is working as expected.

![Screenshot 2022-05-19 at 15 17 17](https://user-images.githubusercontent.com/37012961/169302613-faf42104-1ff7-4113-b74e-9225e18c713d.png)

If we add an attribute with frontend true, we got an error. Due to a mismatch between the content generated by the save function and what we have saved on the DB.
![Screenshot 2022-05-19 at 15 28 15](https://user-images.githubusercontent.com/37012961/169305082-1911e0eb-f48a-4bea-a83f-012f078f3937.png)

https://www.loom.com/share/3b25a296b5744d8da8a457c1f6d5b465

**Comment by luisherranz** [comment]
I don't understand the issue. Could you please elaborate?

**Comment by c4rl0sbr4v0** [comment]
I'm closing the issue as I think is not block hydration experiment related.

I've been testing more cases, like removing the `frontend` attribute from both and switching the selector name, and I guess that is its expected behavior, as we are changing the block attributes and how they are displayed on the fly, causing these mismatches between the JS generated and the DB content.

**Comment by luisherranz** [comment]
Yes, a mismatch is expected because `frontend: true` adds extra markup to the `save.js` output 🙂

> couldn't find what we want to achieve with "Support attribute sourcing."

Should we open an issue about this?

**Comment by luisherranz** [comment]
There you go: https://github.com/WordPress/block-hydration-experiments/issues/27

If you have questions please use the new issue 🙂
