### ISSUE TITLE
Support attribute sourcing

### ISSUE THREAD

**Issue by luisherranz** [WordPress/block-hydration-experiments#27]
I've made a video to explain what we can explore regarding attribute sourcing.
    
<img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/6387036c09424522af773e18866d4a5b-with-play.gif">

https://www.loom.com/share/6387036c09424522af773e18866d4a5b

Resources
  - [Attribute sourcing docs](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-attributes/)
  - [hpq](https://github.com/aduth/hpq)
  - [Editor logic](https://github.com/WordPress/gutenberg/blob/trunk/packages/blocks/src/api/parser/get-block-attributes.js)

_I don't consider this a priority because I'm not sure if it's even worth it. Probably not 🙂_

**Comment by ockham** [comment]
I gave this a stab: #30

(I overall agree with your reasoning @michalczaplinski, but since @luisherranz had laid out the problem so nicely in his video, it felt like a "good first issue" for me to finally play with this repo 😄 )

**Comment by ockham** [comment]
I think we can close this, now that #30 has been merged 🙂

**Comment by luisherranz** [comment]
Now that we've moved the `wp-block` wrapper to PHP, this has started to make sense 🙂
