### ISSUE TITLE
Add the interactive block attributes during server-side rendering 

### ISSUE THREAD

**Issue by luisherranz** [WordPress/block-hydration-experiments#33]
Ok, so we've ended up serializing a lot of stuff in the markup:

```html
<gutenberg-interactive-block
  data-gunteberg-block-type="..."
  data-gunteberg-context-used="..."
  data-gunteberg-context-provided="..."
  data-gunteberg-context-attributes="..."
  data-gunteberg-context-sourced-attributes="..."
  data-gunteberg-context-block-props="..."
  data-gunteberg-context-hydrate="..."
>
  <!-- The real block -->
  <div class="...">...</div>
</gutenberg-interactive-block>
```

The saved markup doesn't seem the best place for this, so I wonder if we should add all those attributes dynamically during the server-side rendering.

Any thoughts? 🙂

**Comment by ockham** [comment]
I think this makes sense 👍 I'd be happy to work on this tomorrow 😄

**Comment by luisherranz** [comment]
Awesome. Let's see if any of that information is missing on the server.
