### ISSUE TITLE
Child using React context throws when there is no parent that provides that context

### ISSUE THREAD

**Issue by luisherranz** [WordPress/block-hydration-experiments#46]
If you add a child block that is using a React context, but there is no parent block present to provide it, the hydration crashes.

At first, I thought it should be a matter of just checking if the provider is there and avoiding the error, but it's true that `useContext` needs to return something. So I'm not sure anymore what should happen here:

- At least, we should provide a better error. 
- Maybe instead of erroring, we should pass `null` to `useContext`, although that may lead to errors in React that may be hard to debug.

I'm open to ideas 🙂🤷‍♂️

<a href="https://www.loom.com/share/8e965b18897a4fe58121a461898c6b42">
    <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/8e965b18897a4fe58121a461898c6b42-with-play.gif">
  </a>

https://www.loom.com/share/8e965b18897a4fe58121a461898c6b42

**Comment by ockham** [comment]
I think it would make sense if "our" `useContext` was consistent with React's and -- in the Absence of a Provider -- returned the default value used [when creating the context](https://github.com/WordPress/block-hydration-experiments/blob/564639c6c767eda8330be86d41eaca6b6534648e/src/context/counter.js#L4):

> `const MyContext = React.createContext(defaultValue);`
> [...]
> The `defaultValue` argument is **only** used when a component does not have a matching Provider above it in the tree. This default value can be helpful for testing components in isolation without wrapping them. Note: passing `undefined` as a Provider value does not cause consuming components to use `defaultValue`.

[(source)](https://reactjs.org/docs/context.html#reactcreatecontext)

**Comment by ockham** [comment]
I'll file a PR for the [above suggestion](https://github.com/WordPress/block-hydration-experiments/issues/46#issuecomment-1208276498) 😊
