### ISSUE TITLE
Duplicated registerBlockType function

### ISSUE THREAD

**Issue by c4rl0sbr4v0** [WordPress/block-hydration-experiments#55]
Right now, we are using the same name for two different functions that do different things, this may cause understanding errors.

[In wordpress-blocks.js file](https://github.com/WordPress/block-hydration-experiments/blob/2d8a9ff55314e6f96a23aac535f1a91c944da213/src/gutenberg-packages/wordpress-blocks.js#L21):
```
export const registerBlockType = (name, { edit, view, ...rest }) => {
	gutenbergRegisterBlockType(name, {
		edit,
		save: Wrapper(view),
		...rest,
	});
};
```

[In gutenberg-packages/frontend.js file](https://github.com/WordPress/block-hydration-experiments/blob/2d8a9ff55314e6f96a23aac535f1a91c944da213/src/gutenberg-packages/frontend.js#L8)
```
export const registerBlockType = (name, Component, options) => {
	blockTypes.set(name, { Component, options });
};
```

Would fit to rename the last one to `setBlockType` instead of `registerBlockType`?
cc @ockham @DAreRodz

**Comment by DAreRodz** [comment]
Each `registerBlockType` indeed has a different purpose (even a different - yet similar API), but they have the same purpose: to keep a registry of block types. The difference is that the first runs in the editor and the second in the frontend.

Maybe we could change the name to clarify that distinction (e.g. `registerFrontendBlockType`)? 🤔

I wouldn't change the name, though; for me, it's enough with the module name you are importing the function from (`gutenberg-packages/frontend`). 🤷

**Comment by c4rl0sbr4v0** [comment]
Although they have the same purpose, I still think that this adds a little overload to the developer, as they will have to check from which module they should import depending on the case, and, also, on the autocomplete, it will appear the same function twice. 😅

**Comment by ockham** [comment]
Yeah, maybe the reason behind using the same name was to signal that it served the same purpose (as David said) and that it simply was the frontend counterpart.

I can see some source for confusion though, so I'm not opposed to changing it to something like `registerFrontendBlockType` or maybe `registerBlockTypeFrontend` (where the `Frontend` is a suffix to keep more consistency with `registerBlockType`, and basically indicates that it's the "frontend" flavor of the same function. Alternatively, it could be read as "registering the block type's frontend", which also kind of works here.)

**Comment by luisherranz** [comment]
Ideally, these two functions should be absorbed (and therefore optional) in the future. The basic information they provide is already present in the `block.json` file.
