### ISSUE TITLE
Code Editor crash

### ISSUE THREAD

**Issue by luisherranz** [WordPress/block-hydration-experiments#9]
The Code Editor is crashing because of this throw:

```js
export const useBlockEnvironment = () => {
  try {
    const env = useReactContext(EnvContext); // Throws in save
    if (env === "frontend") return "frontend";
    return "edit";
  } catch (e) {
  return "save";
  }
};
```

That's a temporary hack to distinguish between the different contexts and obviously we won't try to push it to Gutenberg, so no need to fix. I've just opened the issue so other people finding this problem knows what it is.

**Comment by michalczaplinski** [comment]
Thanks for documenting this! I just came across this very issue 🙂

**Comment by luisherranz** [comment]
Closed as we're not actively working on this experiment anymore, and this works fine in the Directives Hydration.
